version: '3.5'

services:
  client:
    container_name: client
    user: node
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules
       - /usr/src/app/client/.next
    depends_on:
      - server
  server:
    container_name: server
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  dbvol: