import { Button } from "@mui/material";

const Home = () => {
  return (
    <div>
      <header>
        <title>Alias Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>
      <h1 className="text-3xl font-bold underline border border-[red]">
        Homepage
      </h1>
      <Button className="text-[10px] text-white border bg-[black]">
        Primary
      </Button>
    </div>
  );
};

export default Home;
