import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
// import Slider from '@mui/material/Slider';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Alias Check</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline border border-[red]">
        Homepage
      </h1>
      <Button className="text-[10px] text-white border bg-black">
        Primary
      </Button>
    </div>
  );
};

export default Home;
