import { Theme } from "@mui/material";
import { makeStyles } from "@mui/styles";

const top_margin = 10,
  width = "75%",
  height = "90%",
  border = "3px dashed #666";
export default makeStyles((theme: Theme) => ({
  container: {
    borderBottom: "1px solid black",
    position: "relative",
    width: "100%",
    transition: "all 0.2s linear",
    height: "65vh",
    margin: `${top_margin}px 0`,
    marginBottom: `${5 * top_margin}px`,
    // marginBottom: "",
  },
  hero: {
    textAlign: "center",
    fontWeight: "normal",
    fontSize: "3.56rem",
    padding: "0.5rem",
    // backgroundColor: "#09334F",
    // color: "#fff",
  },
  hero_fun: {
    color: "#FAB535",
    margin: "0 2px",
    marginLeft: "4px",
  },
  outerBox: {
    border,
    width,
    height,
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
  },
  topBox: {
    border,
    borderTop: "none",
    width: "25%",
    height: "20px",
    position: "absolute",
    top: `calc(${top_margin}px + 18px)`,
    left: "50%",
    transform: "translate(-50%, -50%)",
    // backgroundColor: "white",
  },
  leftBox: {
    backgroundColor: "white",
    border,
    borderBottom: "none",
    borderLeft: "none",
    width: "12.5%",
    height: "5.1%",
    position: "absolute",
    // top: "calc(100% - 80px)",
    top: height,
    right: width,
  },
  rightBox1: {
    backgroundColor: "white",
    border,
    borderBottom: "none",
    borderRight: "none",
    width: "12.6%",
    height: "20.5%",
    position: "absolute",
    top: `calc(${height} - 15%)`,
    left: width,
  },
  rightBox2: {
    backgroundColor: "white",
    border,
    borderTop: "none",
    borderLeft: "none",
    width: "6.6%",
    height: "10.5%",
    position: "absolute",
    top: `calc(${height} - 15%)`,
    left: width,
  },
  bottom: {
    position: "absolute",
    // bottom: "0",
    top: "calc(100% - 80px)",
    left: "47%",
    transform: "translateX(-50%)",
    // transition: "all 0.6s linear",
  },
  topL: {
    position: "absolute",
  },
  topR: {
    position: "absolute",
    right: "0",
    // left: "100%",
    // left: "calc(100% - 246.77px)",
  },
}));
