import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  title: {
    width: "222px", 
    fontWeight: "bold",   
    fontSize: "49px",    
    height: "132px",  
    marginTop: "0px",   
    marginLeft: "66px",   
  },
  subtitle: {
    color: "#031521",   
    width: "600px",  
    height: "90px", 
    whiteSpace: "pre-wrap", 
    fontWeight: "bold", 
    fontSize: "47px",  
    lineHeight: "70px",   
    letterSpacing: "-0.25px",   
    marginTop: "55px",  
    marginLeft: "145px",
    backgroundColor: "#FAB535", 
    padding: "5px", 
    paddingLeft: "0px", 
    boxShadow: "-16px 0 0 #FAB535 ",
  },
  subtitle2: {
    color: "#031521", 
    width: "356px",
    height: "90px",   
    fontWeight: "bold", 
    fontSize: "47px",  
    lineHeight: "70px",  
    letterSpacing: "-0.25px",
    marginTop: "20px", 
    marginLeft: "145px", 
    backgroundColor: "#FAB535",    
    padding: "5px",   
    paddingLeft: "0px",
    boxShadow: "-20px 0 0 #FAB535 ",
  },
  description: {
    width: "633px",
    height: "128px", 
    color: "#000000",  
    fontSize: "20px",   
    letterSpacing: "-0.25px", 
    marginTop: "50px",  
    marginLeft: "165px",
  },
  // comingsoon: {
  //   color: "#031521",
  //   fontWeight: "bold", 
  //   fontSize: "40px",  
  //   lineHeight: "44px",
  //   letterSpacing: "-0.25px", 
  //   marginTop: "80px",  
  //   marginLeft: "165px",
  //   backgroundClip: "text",
  //   background: "linear-gradient(180deg, #730040 0%, #301cbe 100%)", 
  // }, 
  span: {
    background: "linear-gradient(180deg, #ffd7ff 0%, #ffb6ff 100%)",
    backgroundClip: "text", 
    color: "transparent", 
  },
  top: {
marginLeft: "800px",
display: "flex",
  },
  heroimage: { 
    position: "relative",    
   },
   bottom: {
    marginLeft: "450px", 
    display: "flex",
  },
  aligned: {
    height: "84vh",
    display: "flex", 
    alignItems: "center", 
    gap: "calc(18vh + 5px) calc(18vw + 5px)",
  }, 
}));